import { spawnSync } from 'node:child_process';
import crypto from 'node:crypto';
import { describe, expect, it } from 'vitest';
import { deriveUiPasswordKey, hashUiPassword, normalizeUiPassword, parseUiPasswordHash } from './ui-password-hash.js';

const verify = (hash, candidate) => {
  const parsed = parseUiPasswordHash(hash);
  return parsed !== null
    && crypto.timingSafeEqual(deriveUiPasswordKey(normalizeUiPassword(candidate), parsed.salt), parsed.key);
};

// Mirrors the documented Python recipe for producing OPENCHAMBER_UI_PASSWORD_HASH.
const PYTHON_HASH_SCRIPT = `
import base64, hashlib, os, sys, unicodedata
pw = unicodedata.normalize("NFC", sys.stdin.read()).strip().encode("utf-8")
salt = os.urandom(16)
key = hashlib.scrypt(pw, salt=salt, n=16384, r=8, p=1, dklen=64)
print("scrypt$" + base64.b64encode(salt).decode() + "$" + base64.b64encode(key).decode())
`;

const hasPython = spawnSync('python3', ['--version']).status === 0;

describe('UI password hash', () => {
  it('produces the scrypt$<salt>$<hash> format', () => {
    expect(hashUiPassword('correct horse')).toMatch(/^scrypt\$[A-Za-z0-9+/]+={0,2}\$[A-Za-z0-9+/]+={0,2}$/);
  });

  it('verifies the same normalized password and rejects a different one', () => {
    const hash = hashUiPassword('correct horse');

    expect(verify(hash, '  correct horse\n')).toBe(true);
    expect(verify(hash, 'correct horse!')).toBe(false);
  });

  it('rejects malformed hashes', () => {
    for (const value of ['', 'scrypt$', 'scrypt$c2FsdA==', 'md5$c2FsdA==$aGFzaA==', 'scrypt$c2FsdA==$aGFzaA==']) {
      expect(parseUiPasswordHash(value), value).toBeNull();
    }
  });

  it.skipIf(!hasPython)('verifies a hash generated by Python hashlib.scrypt', () => {
    const result = spawnSync('python3', ['-c', PYTHON_HASH_SCRIPT], { input: 'päss wörd\n', encoding: 'utf8' });
    const hash = result.stdout.trim();

    expect(result.status).toBe(0);
    expect(verify(hash, 'päss wörd')).toBe(true);
    expect(verify(hash, 'pass word')).toBe(false);
  });
});
